version: '3'

services:
  web-app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/ZorkaDjango
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A ZorkaDjango worker -l INFO
    volumes:
      - .:/ZorkaDjango
    depends_on:
      - redis