version: '3'

services:
  web:
    container_name: nazare
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    build: .
    command: celery -A ZorkaDjango worker -l INFO
    depends_on:
      - web
      - redis