version: '3'

services:
  web-app:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/ZorkaDjango
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      -  .:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  worker:
    build: .
    hostname: worker
    entrypoint: celery
    command: -A ZorkaDjango worker -l INFO
    volumes:
      - .:/ZorkaDjango
    links:
      - redis
    depends_on:
      - redis