# Generated by Django 4.1 on 2023-12-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.IntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('amount_guests', models.IntegerField()),
                ('amount_children', models.IntegerField()),
                ('client_name', models.CharField(max_length=50)),
                ('client_surname', models.CharField(max_length=50)),
                ('client_second_name', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_number', models.CharField(max_length=50)),
                ('guest_id', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('total_sum', models.FloatField()),
            ],
        ),
    ]
