# Generated by Django 4.1 on 2023-12-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount_children',
            new_name='children_count',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='amount_guests',
            new_name='guests_count',
        ),
    ]
