# Generated by Django 4.2.4 on 2023-08-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('guests', models.IntegerField(verbose_name='Кол-во гостей')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('sleepPlace', models.IntegerField(verbose_name='Кол-во спальных мест')),
                ('isWifi', models.BooleanField(verbose_name='Wi-Fi')),
            ],
        ),
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Обратный звонок', 'verbose_name_plural': 'Обратные звонки'},
        ),
        migrations.AlterField(
            model_name='callback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
