# Generated by Django 4.2.4 on 2023-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
