# Generated by Django 4.2.4 on 2023-08-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_apartment_options_apartmentphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentPhoto',
        ),
    ]
