# Generated by Django 2.2 on 2023-09-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_photo_photocategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotoCategory',
        ),
    ]
