# Generated by Django 2.2 on 2023-09-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20230915_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('param', models.CharField(max_length=100, verbose_name='Параметр (English)')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='isWifi',
        ),
        migrations.AddField(
            model_name='apartment',
            name='dailyPrice',
            field=models.IntegerField(default=0, verbose_name='Суточная стоимость (BYN)'),
        ),
    ]
