# Generated by Django 2.2 on 2023-09-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20230915_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Электронная почта', 'verbose_name_plural': 'Электронные почты'},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='isWifi',
        ),
        migrations.AddField(
            model_name='apartment',
            name='dailyPrice',
            field=models.IntegerField(default=0, verbose_name='Суточная стоимость (BYN)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='address',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес'),
        ),
    ]
