# Generated by Django 2.2 on 2023-09-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Псевдоним (English)'),
        ),
    ]
