# Generated by Django 2.2 on 2023-10-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20230924_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, verbose_name='Название (English)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Псевдоним (English)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PageSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Псевдоним (English)')),
            ],
            options={
                'verbose_name': 'Псевдоним страницы',
                'verbose_name_plural': 'Псевдонимы страниц',
            },
        ),
        migrations.AddField(
            model_name='callback',
            name='placeApplication',
            field=models.CharField(default='', max_length=200, verbose_name='Место подачи заявки'),
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(default='', verbose_name='Описание (English)'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(default='', max_length=100, verbose_name='Название (English)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, verbose_name='Название (English)')),
                ('icon', models.CharField(max_length=255, verbose_name='Иконка (Font awesome)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Псевдоним (English)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Category', verbose_name='Категория')),
                ('page_slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.PageSlug', verbose_name='Псевдоним страницы (English)')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
    ]
