# Generated by Django 2.2 on 2023-10-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20231001_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='page_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.PageSlug', verbose_name='Псевдоним страницы'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Псевдоним (English)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
